// PathClassifier unit tests — the file attribute tagging authority.
//
// RED material comes from the verified D1 defects
// (benchmarks/repo-qa/ANALYSIS-insight-verification.md):
//   - chi: _examples/*/main.go analyzed as production entry points
//   - guzzle: tests/**, *Test.php analyzed as production
//   - pocketbase: ui/public/libs/uplot/uplot.iife.js (vendored minified)
//     supplying entry points / cycles / high-complexity stats

#include <lci/path_classifier.h>

#include <gtest/gtest.h>

#include <string>

namespace lci {
namespace {

// -- Built-in defaults: Go ----------------------------------------------------

TEST(PathClassifierTest, GoTestFile) {
    PathClassifier c;
    EXPECT_EQ(c.classify("middleware/logger_test.go"), PathAttr::Test);
    EXPECT_EQ(c.classify("mux_test.go"), PathAttr::Test);
}

TEST(PathClassifierTest, GoUnderscoreDirIsExample) {
    PathClassifier c;
    // chi D1: 12/12 entry points were _examples/*/main.go.
    EXPECT_EQ(c.classify("_examples/custom-handler/main.go"),
              PathAttr::Example);
    EXPECT_EQ(c.classify("_examples/rest/main.go"), PathAttr::Example);
}

TEST(PathClassifierTest, GoTestdataDir) {
    PathClassifier c;
    EXPECT_EQ(c.classify("pkg/parser/testdata/input.go"), PathAttr::Test);
}

// -- Built-in defaults: PHP / JS / TS -----------------------------------------

TEST(PathClassifierTest, PhpTestsDirAndSuffix) {
    PathClassifier c;
    // guzzle D1: tests/Handler classified as API Layer; 4/12 entry points
    // were PHPUnit test methods.
    EXPECT_EQ(c.classify("tests/Handler/CurlFactoryTest.php"), PathAttr::Test);
    EXPECT_EQ(c.classify("tests/ClientTest.php"), PathAttr::Test);
    EXPECT_EQ(c.classify("src/HandlerTest.php"), PathAttr::Test);
}

TEST(PathClassifierTest, JsTsTestPatterns) {
    PathClassifier c;
    EXPECT_EQ(c.classify("src/__tests__/router.js"), PathAttr::Test);
    EXPECT_EQ(c.classify("src/router.test.ts"), PathAttr::Test);
    EXPECT_EQ(c.classify("src/router.spec.tsx"), PathAttr::Test);
    EXPECT_EQ(c.classify("tests/e2e/login.py"), PathAttr::Test);
    EXPECT_EQ(c.classify("scripts/test_forge.py"), PathAttr::Test);
    EXPECT_EQ(c.classify("tests/conftest.py"), PathAttr::Test);
}

// -- Vendored ------------------------------------------------------------------

TEST(PathClassifierTest, VendorDirs) {
    PathClassifier c;
    EXPECT_EQ(c.classify("vendor/guzzlehttp/psr7/src/Uri.php"),
              PathAttr::Vendored);
    EXPECT_EQ(c.classify("node_modules/react/index.js"), PathAttr::Vendored);
    EXPECT_EQ(c.classify("third_party/zlib/inflate.c"), PathAttr::Vendored);
}

TEST(PathClassifierTest, MinifiedBasename) {
    PathClassifier c;
    EXPECT_EQ(c.classify("ui/public/js/app.min.js"), PathAttr::Vendored);
    EXPECT_EQ(c.classify("assets/style.min.css"), PathAttr::Vendored);
}

TEST(PathClassifierTest, MinifiedContentHeuristic) {
    PathClassifier c;
    // pocketbase D1: ui/public/libs/uplot/uplot.iife.js — one enormous line.
    std::string minified(50000, 'x');
    EXPECT_EQ(c.classify("ui/public/libs/uplot/uplot.iife.js", minified),
              PathAttr::Vendored);
    // Normal multi-line code stays production.
    std::string code;
    for (int i = 0; i < 500; ++i) code += "const x = 1;\n";
    EXPECT_EQ(c.classify("ui/src/app.js", code), PathAttr::Production);
}

// -- Generated -----------------------------------------------------------------

TEST(PathClassifierTest, GeneratedPatterns) {
    PathClassifier c;
    EXPECT_EQ(c.classify("api/service.pb.go"), PathAttr::Generated);
    EXPECT_EQ(c.classify("proto/service_pb2.py"), PathAttr::Generated);
    EXPECT_EQ(c.classify("src/schema_generated.ts"), PathAttr::Generated);
    EXPECT_EQ(c.classify("types/global.d.ts"), PathAttr::Generated);
    EXPECT_EQ(c.classify("pkg/apis/zz_generated.deepcopy.go"),
              PathAttr::Generated);
}

TEST(PathClassifierTest, GeneratedHeaderContent) {
    PathClassifier c;
    EXPECT_EQ(c.classify("internal/types/types.go",
                         "// Code generated by jsvm. DO NOT EDIT.\n"
                         "package types\n"),
              PathAttr::Generated);
    EXPECT_EQ(c.classify("internal/types/types.go", "package types\n"),
              PathAttr::Production);
}

// -- Docs ----------------------------------------------------------------------

TEST(PathClassifierTest, DocsDirAndMarkdown) {
    PathClassifier c;
    EXPECT_EQ(c.classify("docs/guide/install.js"), PathAttr::Docs);
    EXPECT_EQ(c.classify("README.md"), PathAttr::Docs);
}

// -- Production stays production ----------------------------------------------

TEST(PathClassifierTest, ProductionPaths) {
    PathClassifier c;
    EXPECT_EQ(c.classify("mux.go"), PathAttr::Production);
    EXPECT_EQ(c.classify("middleware/logger.go"), PathAttr::Production);
    EXPECT_EQ(c.classify("src/Client.php"), PathAttr::Production);
    // "testing"-adjacent words must not fuzzy-match.
    EXPECT_EQ(c.classify("src/contest/rank.go"), PathAttr::Production);
    EXPECT_EQ(c.classify("src/attestation/verify.go"), PathAttr::Production);
}

// -- Precedence ----------------------------------------------------------------

TEST(PathClassifierTest, VendoredBeatsTest) {
    PathClassifier c;
    EXPECT_EQ(c.classify("vendor/pkg/foo_test.go"), PathAttr::Vendored);
    EXPECT_EQ(c.classify("node_modules/lib/__tests__/a.js"),
              PathAttr::Vendored);
}

// -- Config rules override builtins -------------------------------------------

TEST(PathClassifierTest, ConfigRuleAddsTag) {
    PathClassifier c({{PathAttr::Test, "src/legacy_tests/"}});
    EXPECT_EQ(c.classify("src/legacy_tests/old.go"), PathAttr::Test);
}

TEST(PathClassifierTest, ConfigProductionOverridesBuiltin) {
    PathClassifier c({{PathAttr::Production, "vendor/mycompany/"}});
    EXPECT_EQ(c.classify("vendor/mycompany/core.go"), PathAttr::Production);
    EXPECT_EQ(c.classify("vendor/other/core.go"), PathAttr::Vendored);
}

TEST(PathClassifierTest, ConfigBasenameGlob) {
    PathClassifier c({{PathAttr::Vendored, "*.iife.js"}});
    EXPECT_EQ(c.classify("ui/public/libs/uplot/uplot.iife.js"),
              PathAttr::Vendored);
}

TEST(PathClassifierTest, ConfigProductionBeatsContentHeuristic) {
    PathClassifier c({{PathAttr::Production, "big/blob.js"}});
    std::string minified(50000, 'x');
    EXPECT_EQ(c.classify("big/blob.js", minified), PathAttr::Production);
}

// -- Names ---------------------------------------------------------------------

TEST(PathClassifierTest, NameRoundTrip) {
    for (int i = 0; i < kPathAttrCount; ++i) {
        auto attr = static_cast<PathAttr>(i);
        PathAttr parsed{};
        ASSERT_TRUE(PathClassifier::parse(PathClassifier::name(attr), parsed));
        EXPECT_EQ(parsed, attr);
    }
    PathAttr out{};
    EXPECT_FALSE(PathClassifier::parse("bogus", out));
}

}  // namespace
}  // namespace lci
